name: Build and deploy Flutter web app

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-web/**'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio-web repo
        uses: actions/checkout@v2
        with:
          repository: issaloubani/portfolio-web
          ref: master
      
      - name: Check workspace contents
        run: ls ${{ github.workspace }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          
      - name: Get dependencies
        working-directory: ${{ github.workspace }}
        run: flutter pub get
        
      - name: Build web app
        run: flutter build web --release --web-renderer=html --no-sound-null-safety
        working-directory: ${{ github.workspace }}
      
      - name: Check workspace contents
        run: ls ${{ github.workspace }}
        
      - name: Check workspace contents
        run: ls ${{ github.workspace }}/build        
      
      - name: Copy built files to main branch
        run: |
          cd build/web
          git init
          git config --global user.email "issa.loubani.5@gmail.com"
          git config --global user.name "Issa Loubani"
          git add -A
          git commit -m "Update web app"
          git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
