name: Build and deploy Flutter web app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout portfolio-web repo
        uses: actions/checkout@v2
        with:
          repository: issaloubani/portfolio-web
          ref: master
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.5'
          
      - name: Get dependencies
        working-directory: ${{ github.workspace }}/portfolio-web
        run: |
          ls
          flutter pub get
        
      - name: Build web app
        run: flutter build web --release --web-renderer=html --no-sound-null-safety
        working-directory: ${{ github.workspace }}/portfolio-web
        
      - name: Copy built files to main branch
        run: |
          rm -rf ./build
          mkdir build
          cp -r ./portfolio-web/build/web/* ./build/
          git config --global user.email "issa.loubani.5@gmail.com"
          git config --global user.name "Issa Loubani"
          git add -A
          git commit -m "Update web app"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
